"""empty message

Revision ID: c40cf10854cb
Revises: 9ff26de08bf4
Create Date: 2022-08-11 07:14:05.178683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40cf10854cb'
down_revision = '9ff26de08bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
